import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navigation } from "../components/Navigation";
import { ReactQueryProvider } from "./ReactQueryProvider";
import { FavoriteCarsProvider } from "./providers/FavoriteCarsProvider";
import AuthProvider from "./providers/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navigation />
          <ReactQueryProvider>
            <FavoriteCarsProvider>{children}</FavoriteCarsProvider>
          </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
