import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navigation } from "../components/Navigation";
import { ReactQueryProvider } from "./ReactQueryProvider";
import { AuthProvider } from "./AuthProvider";
import { FavoriteCarsProvider } from "./providers/FavoriteCarsProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navigation />
          <ReactQueryProvider>
            <FavoriteCarsProvider>{children}</FavoriteCarsProvider>
          </ReactQueryProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
